### ISSUE TITLE
Can you provide the configuration file for the conda environment

### ISSUE THREAD

**Issue by Lumen97** [Saoge123/PocketFlow#2]

**Comment by Lumen97** [comment]
Loading model ...
Generating molecules ...
Traceback (most recent call last):
  File "main_generate.py", line 94, in <module>
    generate.generate(data, num_gen=args.num_gen, rec_name=args.name, with_print=args.with_print,
  File "/home/user/software/PocketFlow-master/pocket_flow/generate.py", line 358, in generate
    out = self.run(data_clone)
  File "/home/user/software/PocketFlow-master/pocket_flow/generate.py", line 265, in run
    h_cpx = self.model.encoder(
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/software/PocketFlow-master/pocket_flow/gdbp_model/encoder.py", line 48, in forward
    delta_h = interaction(h, edge_index, edge_feature, edge_vector, edge_dist, annealing=annealing)
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/software/PocketFlow-master/pocket_flow/gdbp_model/layers.py", line 278, in forward
    out_sca, out_vec = self.msg_att(x, (msg_j_sca, msg_j_vec), row)
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/software/PocketFlow-master/pocket_flow/gdbp_model/layers.py", line 174, in forward
    scatter_softmax(alpha[0], edge_index_i, dim=0),
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch_scatter/composite/softmax.py", line 18, in scatter_softmax
    max_value_per_index = scatter_max(
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/home/user/miniconda3/envs/pocketflow/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with CUDA support

**Comment by Saoge123** [comment]
Hi
I have uploaded [requirements.txt](https://github.com/Saoge123/PocketFlow/blob/master/requirements.txt) of our conda env.

**Comment by Lumen97** [comment]
> Hi I have uploaded [requirements.txt](https://github.com/Saoge123/PocketFlow/blob/master/requirements.txt) of our conda env.

Thanks for your previously provided conda environment, I have used it and successfully run PocketFlow.

**Comment by chemgirl97** [comment]
I installed the requirements.txt file.

An error occurred during installation.
---------------------------------------------------------------------------------------------
Collecting defusedxml (from -r requirements.txt (line 39))
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
ERROR: Could not find a version that satisfies the requirement dgl-cu113==0.9.0 (from versions: none)
ERROR: No matching distribution found for dgl-cu113==0.9.0
----------------------------------------------------------------------------------------------

**Comment by Lumen97** [comment]
> I installed the requirements.txt file.
> 
> ## An error occurred during installation.
> ## Collecting defusedxml (from -r requirements.txt (line 39))
> Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
> ERROR: Could not find a version that satisfies the requirement dgl-cu113==0.9.0 (from versions: none)
> ERROR: No matching distribution found for dgl-cu113==0.9.0

I didn't install completely according to requirements.txt, but found the correct version of torch_scatter. Below is my conda environment configuration file

```
name: pocketflow
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py38h06a4308_0
  - aiohttp=3.9.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=23.1.0=py38h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py38h06a4308_0
  - boost=1.70.0=py38h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cryptography=42.0.5=py38hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - cudnn=8.9.2.26=cuda11_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - glew=2.1.0=h295c915_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glm=0.9.9.8=h00ab1b0_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py38h06a4308_0
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py38he1ff14a_4
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h0b41bf4_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hac7e632_1003
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libzip=1.8.0=h6ac8c49_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.4.1=py38h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - multidict=6.0.4=py38h5eee18b_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.20.3=py38h7820934_1
  - numpy-base=1.20.3=py38h7e635b3_1
  - oauthlib=3.2.2=py38h06a4308_0
  - openbabel=3.1.1=py38hd2c4bc0_2
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.1=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.0.0=py38hdc8b05c_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py38h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - ply=3.11=py_1
  - pmw=2.0.1=py38h578d9bd_1008
  - protobuf=3.20.3=py38h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycairo=1.25.0=py38h1a1917b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pymol-open-source=2.5.0=py38h9174eab_6
  - pyopenssl=24.0.0=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.0=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - qt-main=5.15.2=h7358343_9
  - rdkit=2019.09.3=py38hb31dc5d_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=68.2.2=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py38h06a4308_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - torchaudio=0.12.0=py38_cu113
  - torchvision=0.13.0=py38_cu113
  - typing_extensions=4.9.0=py38h06a4308_1
  - urllib3=2.1.0=py38h06a4308_1
  - werkzeug=2.3.8=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_0
  - yarl=1.9.3=py38h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - contourpy==1.1.1
      - cycler==0.12.1
      - easydict==1.13
      - fonttools==4.49.0
      - importlib-resources==6.3.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - libnetcdf==0.0.1
      - lmdb==1.4.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - psutil==5.9.8
      - pyparsing==3.1.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - threadpoolctl==3.3.0
      - torch-cluster==1.6.3
      - torch-geometric==2.1.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.1+pt112cu113
      - tqdm==4.66.2
      - zipp==3.18.0
prefix: /home/user/miniconda3/envs/pocketflow
```

**Comment by Saoge123** [comment]
Hi, PocketFlow dose not depend on dgl, you can skip this package.

**Comment by Lyueyang2020** [comment]
您好，我尝试了您的模型，使用系统win11，并测试“python main_generate.py -pkt test_samples/test_pocket10/1bvr_C_rec_pocket10-surf.pdb --ckpt ckpt/ZINC-pretrained-255000.pt -n 100 -d cuda:0 --root_path gen_results --name 1bvr -at 1.0 -bt 1.0 --max_atom_num 35 -ft 0.5 -cm True --with_print True”，已成功运行。
  但是当我想生成自己的pocket时，”from pocket_flow import SplitPocket, Protein, Ligand“会报错“ModuleNotFoundError: No module named 'pocket_flow'”，您知道如何解决吗？
  还有我已经安装了cuda( torch.version.cuda'11.6'),但是当使用“-d cuda:1”时会报错“RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.”。
  由于本人毫无编程基础无法解决以上问题，如您能解答将万分感激。
