### ISSUE TITLE
Request for Code for Metrics Calculation

### ISSUE THREAD

**Issue by HShokaku** [Saoge123/PocketFlow#4]
Hi,

Thanks for your impressive work!

I noticed the QED metric of Crossdocked2020 test set as reference in your paper is 0.531 ± 0.210. However, most SBDD papers report results around ~0.48 for this metric. 

I could not find the code to calculate metrics (including SAscores etc.) in your repository. Could you please provide it?

@Saoge123

**Comment by Saoge123** [comment]
Hi, CrossDocked2020 is based on the data of PDBbind, and produced by the manner of coss-docking. There are a lot of ligands that reappear many times. We remove the repeating molecules when compute metrics (about 11700 different molecules obtained).

**Comment by HShokaku** [comment]
> Hi, CrossDocked2020 is based on the data of PDBbind, and produced by the manner of coss-docking. There are a lot of ligands that reappear many times. We remove the repeating molecules when compute metrics (about 11700 different molecules obtained).

Got it! Thank you!
