### ISSUE TITLE
Code for Metrics Calculation

### ISSUE THREAD

**Issue by lfs119** [Saoge123/PocketFlow#7]
hi, Thank you so much for publishing the code and it's a pretty work. 
I'm a relative newcomer and could not find the instruction to calculate metrics (including SAscores etc.). Could you offer some information?

**Comment by Saoge123** [comment]
hi，you can use rdkit to compute those metrics. SA score is also in: https://github.com/rdkit/rdkit/tree/master/Contrib/SA_Score

**Comment by lfs119** [comment]
ok, Thanks!
